# Generated by Django 3.2.8 on 2021-10-30 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='tutorship',
        ),
    ]
