# Generated by Django 3.2.8 on 2021-10-30 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthentication', '0002_tutorcourse'),
        ('Student', '0002_remove_request_tutorship'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='tutor_requested',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_requested', to='UserAuthentication.user'),
            preserve_default=False,
        ),
    ]
