# Generated by Django 3.2.5 on 2021-10-21 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_people', models.IntegerField()),
                ('amount_per_person', models.IntegerField()),
                ('increment_per_half_hour', models.IntegerField()),
                ('state', models.IntegerField()),
                ('type_session', models.IntegerField()),
                ('type_mode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TutorshipAvailableSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('start_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
                ('id_tutorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutorship.tutorship')),
            ],
        ),
        migrations.CreateModel(
            name='CourseTutorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tutorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutorship.tutorship')),
            ],
        ),
    ]
