# Generated by Django 3.2.5 on 2021-10-20 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxPeople', models.IntegerField()),
                ('amountPerPerson', models.IntegerField()),
                ('incrementPerHalfHour', models.IntegerField()),
                ('state', models.IntegerField()),
                ('typeSession', models.IntegerField()),
                ('typeMode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TutorshipAvailableSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('startHour', models.TimeField()),
                ('endHour', models.TimeField()),
                ('idTutorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutorship.tutorship')),
            ],
        ),
        migrations.CreateModel(
            name='CourseTutorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTutorship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tutorship.tutorship')),
            ],
        ),
    ]
