# Generated by Django 3.2.5 on 2021-10-22 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
        ('Tutorship', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetutorship',
            name='id_course',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Course.course'),
        ),
    ]
