# Generated by Django 3.2.8 on 2021-11-01 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorship', '0002_tutorshipscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorship',
            name='state',
            field=models.CharField(choices=[('AP', 'Aprobada'), ('DN', 'Realizada')], default='AP', max_length=2),
        ),
    ]
