# Generated by Django 3.2.8 on 2021-10-26 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorship', '0003_auto_20211026_1406'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutoravailableschedule',
            old_name='user_id',
            new_name='user',
        ),
    ]
