# Generated by Django 3.2.8 on 2021-11-01 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
        ('Tutorship', '0003_alter_tutorship_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorship',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='tutorship',
            name='start_time',
        ),
        migrations.AddField(
            model_name='tutorship',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.request'),
        ),
        migrations.DeleteModel(
            name='TutorshipCourse',
        ),
    ]
