# Generated by Django 3.2.8 on 2021-10-20 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceTutorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Resource.resource')),
            ],
        ),
    ]
