# Generated by Django 3.2.5 on 2021-10-22 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorship', '0001_initial'),
        ('Resource', '0002_resourcetutorship'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcetutorship',
            name='id_tutorship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tutorship.tutorship'),
        ),
    ]
