# Generated by Django 3.2.5 on 2021-10-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthentication', '0002_alter_user_photo_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_profile',
            field=models.CharField(max_length=300),
        ),
    ]
