# Generated by Django 3.2.8 on 2021-10-29 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Modality', '0001_initial'),
        ('Session', '0001_initial'),
        ('Tutor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='type_session',
        ),
        migrations.AddField(
            model_name='tutor',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Session.session'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='type_mode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Modality.modality'),
        ),
    ]
