# Generated by Django 3.2.8 on 2021-10-29 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
        ('Tutor', '0003_auto_20211029_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='amount_per_person',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='increment_per_half_hour',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='payment_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Payment.payment'),
        ),
    ]
